FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_APP app

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn==20.0

COPY wsgi.py ./wsgi.py
COPY app/. ./app/

CMD ["gunicorn","--bind","0.0.0.0:5000","wsgi"]
